### ISSUE TITLE
Credits to add

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/cremma-wikipedia#2]
```
authors:
  - name: 
    surname: Antoine
    type: person
  - name: Guichard
    surname: Morgane
    type: person
  - name: Chagué
    surname: Alix
    type: person
  - name: Chateau
    surname: Emmanuel
    type: person
  - name: Razafindrakoto
    surname: Elise
    type: person
  - name: Foisy-Marquis
    surname: Clémence
    type: person
  - name: Hennequart
    surname: Pauline
    type: person
  - name: Mellet
    surname: Margot
    type: person
  - name: Jia
    surname: Arilys
    type: person
  - name: Verstaete
    surname: Mathilde
    type: person
  - name: Krause
    surname: Lena
    type: person
  - name: Mozin
    surname: Zoé
    type: person
  - name: Bourgeois
    surname: Camille
    type: person
  - name: Delattre
    surname: Camille
    type: person
  - name: Ferretti
    surname: Giulia
    type: person
  - name: Vitali Rosati
    surname: Marcello
    type: person
  - name: Delannay
    surname: Roch
    type: person
  - name: Lescouet
    surname: Emmanuelle
    type: person
```
